import pygame

from .controls import LB

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_CENTER = (SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2)
screen = pygame.display.set_mode(SCREEN_SIZE)
BOARDER = 20
LINE_WIDTH = 4
channel_i = 0

POINT_DIAMETER = SCREEN_HEIGHT / 75

SELECT_MOD = LB

GREEN = (166, 227, 161)
BASE = (24, 24, 37)
PEACH = (250, 179, 135)
LAVENDER = (180, 190, 254)
SURFACE_1 = (69, 71, 90)
SURFACE_0 = (49, 50, 68)
YELLOW = (249, 226, 175)
ROSEWATER = (245, 224, 220)
RED = (243, 139, 168)
SURFACE_2 = (88, 91, 112)
TEXT = (205, 214, 244)
CRUST = (17, 17, 27)
SAPHIRE = (116, 199, 236)

BACKGROUND_COLOR = BASE
TEXT_COLOR_1 = PEACH
TEXT_COLOR_2 = SURFACE_2
POINT_COLOR = ROSEWATER
ACCENT_COLOR = PEACH
LIMIT_COLOR = RED

SIDE_BARS_W = SCREEN_WIDTH * 0.125
MAIN_VIEW_W = SCREEN_WIDTH * 0.75
BUTTON_H = SCREEN_CENTER[1] * 0.75 / 2
HINT_BAR_H = SCREEN_HEIGHT * 0.1

STEP_BUTTON_BOUNDING_BOX = pygame.Rect(
    SIDE_BARS_W + MAIN_VIEW_W * 0.2,
    SCREEN_CENTER[1] + (SCREEN_CENTER[1] - BUTTON_H * 2),
    MAIN_VIEW_W * 0.8,
    BUTTON_H * 2,
)
BUTTON_BOARDER_W = int((STEP_BUTTON_BOUNDING_BOX.width / 8) * 0.06)
BOARDER_RADIUS = 5

PIANO_W = MAIN_VIEW_W
PIANO_H = SCREEN_CENTER[1] - STEP_BUTTON_BOUNDING_BOX.height
# PIANO_SPINE_W = PIANO_W / 88
# white-keys-per-octave * n-full-octaves + len([a0, b0, c8])
N_OCTAVES = 7
n_white_keys = 7 * N_OCTAVES
n_black_keys = 5 * N_OCTAVES
PIANO_BLACK_H = PIANO_H * 0.5
OCTAVE_W = PIANO_W / 7
PIANO_WHITE_W = OCTAVE_W / 7
PIANO_BLACK_W = OCTAVE_W / 12

CHANNEL_MID_X = (SIDE_BARS_W + STEP_BUTTON_BOUNDING_BOX.left) / 2


def select_mod_pressed(controller):
    return controller.is_pressed(SELECT_MOD)
